// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function getSupabaseSessionPoolerUrl(databaseUrl?: string) {
  if (!databaseUrl) {
    return undefined;
  }

  const url = new URL(databaseUrl);

  if (!url.hostname.includes(".pooler.supabase.com")) {
    return databaseUrl;
  }

  url.port = "5432";
  url.searchParams.delete("pgbouncer");
  url.searchParams.delete("sslmode");

  return url.toString();
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url:
      process.env["DIRECT_URL"] ??
      process.env["SESSION_DATABASE_URL"] ??
      getSupabaseSessionPoolerUrl(process.env["DATABASE_URL"]),
  },
});
